services:
  # Backend Web Service (Django)
  - type: web
    name: smartstock-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python smartstock_backend/manage.py migrate && gunicorn --chdir smartstock_backend smartstock_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "True"
      - key: PYTHON_VERSION
        value: 3.12.8

  # Frontend Static Site (React/Vite)
  - type: web
    runtime: static
    name: smartstock-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: smartstock-backend
          property: host
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: smartstock-backend
          property: host
