# Generated by Django 6.0.3 on 2026-03-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('slow_moving', 'Slow Moving'), ('demand_increase', 'Demand Increase'), ('demand_decrease', 'Demand Decrease'), ('seasonal', 'Seasonal'), ('reorder_recommendation', 'Reorder Recommendation'), ('expiry_alert', 'Expiry Alert'), ('profit_optimization', 'Profit Optimization')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
