# Generated by Django 6.0.3 on 2026-03-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_engine', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='accounts.retailer'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='accounts.retailer'),
        ),
        migrations.AddIndex(
            model_name='saleshistory',
            index=models.Index(fields=['retailer', 'product', 'date'], name='ai_engine_s_retaile_da12af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleshistory',
            unique_together={('retailer', 'product', 'date')},
        ),
    ]
