# Generated by Django 6.0.3 on 2026-03-05 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('order_update', 'Order Update'), ('delivery_update', 'Delivery Update'), ('low_stock', 'Low Stock'), ('reorder_suggestion', 'Reorder Suggestion'), ('payment_update', 'Payment Update'), ('system', 'System')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
