# Generated by Django 6.0.3 on 2026-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_items',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
