# Generated by Django 6.0.3 on 2026-03-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('net_banking', 'Net Banking'), ('cod', 'Cash on Delivery')], max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
