# Generated by Django 6.0.3 on 2026-03-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_remove_payment_amount_remove_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_score', models.IntegerField(default=100)),
                ('total_credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overdue_count', models.IntegerField(default=0)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='accounts.retailer')),
            ],
            options={
                'verbose_name': 'Retailer Credit Profile',
                'verbose_name_plural': 'Retailer Credit Profiles',
            },
        ),
    ]
