# Generated by Django 6.0.3 on 2026-03-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('total_gmv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('new_retailers', models.PositiveIntegerField(default=0)),
                ('new_wholesalers', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('top_purchased_categories_json', models.JSONField(default=dict)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.retailer')),
            ],
            options={
                'unique_together': {('retailer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WholesalerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('top_selling_products_json', models.JSONField(default=dict)),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.wholesaler')),
            ],
            options={
                'unique_together': {('wholesaler', 'date')},
            },
        ),
    ]
